---
# handlers file for nginx

- name: Check HTTP Service
  uri:
    url: http://{{ ansible_ssh_host }}
    status_code: 200

- name: Reload Firewall
  service:
    name: firewalld
    state: reloaded
